node {
  stage 'build app'
  openshiftBuild(namespace: 'demo', buildConfig: 'welcome', showBuildLogs: 'true')
  stage 'execute image scan'
    openshift.withCluster() {
	def models = openshift.process( "demo//image-inspector-template", "-p", "APPLICATION_NAME=image-inspector", "-p", "IMAGE_URL=docker-registry-default.apps.dwojciec.com/demo/welcome:latest")
        echo "Creating this template will instantiate ${models.size()} objects"
        def created = openshift.create( models )
        echo "Application created"
	created.describe()    
	
	def pod-inspect  = created.narrow("pod")
	def result = pod-inspect.log('-f')
	echo "The logs operation require ${result.actions.size()} oc interactions"
        // You can even see exactly what oc command was executed.
        echo "Logs executed: ${result.actions[0].cmd}"

        // And even obtain the standard output and standard error of the command.
        def logsString = result.actions[0].out
        def logsErr = result.actions[0].err
	    echo "Logs logString: ${logsString}"
	    echo "Log Err : ${logErr}"
    
    }
  stage 'review report'
  input "Do you want to deploy the application ?"

  stage 'deploy app'
  openshiftDeploy(namespace: 'demo', deploymentConfig: 'welcome')
  openshiftDeleteResourceByLabels(namespace: 'demo', apiURL: 'https://openshift.default.svc.cluster.local', authToken: '', types: 'route,svc,pod', keys: 'app' , values: 'image-inspector', verbose: 'false')
  sh "oc get all -l app=image-inspector" 	
}
